name: Create Downloadable Release

on:
  push:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Update Externals
      run: |
        git submodule update --remote
    - name: commit changed files
      uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Apply automatic changes
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#    - name: Build and test with Jekyll
#      run: |
#        gem install bundler
#        bundle install --jobs 4 --retry 3
#        bundle exec jekyll build --config "_config.yml,_config_prod.yml" --profile
    - name: generate fake site for quicker testing
      run: |
        mkdir ./_site
        echo "this is foo.txt" > ./_site/foo.txt
        echo "<p>this is bar.html</p>" > ./_site/bar.html
        echo "<p>this is index.html</p>" > ./_site/index.html
    - name: Generate list of resources to manifest.txt
      run: |
        find ./_site -type f > ./_site/manifest.txt
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
