name: Create Downloadable Release

on:
  push:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Update Externals
      run: |
        git submodule update --remote
    - name: commit changed files
      uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Apply automatic changes
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and test with Jekyll
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build --config "_config.yml,_config_prod.yml" --profile
    - name: Generate list of resources to manifest.txt
      run: |
        find ./_site -type f > ./_site/manifest.txt
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site
